language: r
warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages:
  - hadley/testthat
  - hadley/httr
  - jimhester/covr
  - yihui/knitr
  - jeroenooms/jsonlite
  - jeroenooms/curl
  
after_success:
  - Rscript -e 'library(covr);coveralls()'
  
notifications:
  email:
    on_success: never
    on_failure: always
